id: IA65A22A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T06:05:30+00:00'
last_modified: '2022-06-10T05:19:49.123567+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1629
  title: དགེ་ལྡན་མཁས་གྲུབ་དག་གི་རྫོགས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B4EA:
      image_group_id: I1KG1631
      title: Volume 1 of dge ldan mkhas grub dag gi rdzogs skor phyogs bsgrigs
      total_pages: 308
      order: 1
      base_file: B4EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
